### ISSUE TITLE
podman v4.5.1 released

### ISSUE THREAD

**Issue by calvin2021y** [mgoltzsche/podman-static#63]
podman v4.5.1 released

**Comment by calvin2021y** [comment]
I try `podman-static` on debian 12, get this error:

```sh
WARN[0002] Failed to add conmon to cgroupfs sandbox cgroup: creating cgroup path /libpod_parent/conmon: write /sys/fs/cgroup/cgroup.subtree_control: invalid argument 
Error: OCI runtime error: crun: writing file `/sys/fs/cgroup/cgroup.subtree_control`: Invalid argument
```

**Comment by mgoltzsche** [comment]
I released podman-static [v4.5.1](https://github.com/mgoltzsche/podman-static/releases/tag/v4.5.1) now.
Maybe that resolves your issue. If case it doesn't, feel free to open a new issue.

**Comment by calvin2021y** [comment]
thanks. issue still exists.

I find this after upgrade kernel, will test office podman to confirm
